/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PINView.h"
#import "UITableViewDataSource.h"

@class UITableView, PreferencesTextTableCell, UITextField;

@interface AlphanumericPINView : PINView <UITableViewDataSource> {
	UITextField* _passcodeField;
	PreferencesTextTableCell* _cell;
	UITableView* _table;
}
-(id)initWithFrame:(CGRect)frame;
-(void)layoutSubviews;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)setBlocked:(BOOL)blocked;
-(BOOL)keyboardInputChanged:(id)changed;
-(void)showError:(id)error animate:(BOOL)animate;
-(void)dealloc;
-(id)stringValue;
-(void)okButtonPressed:(id)pressed;
-(void)hidePasscodeField:(BOOL)field;
-(BOOL)becomeFirstResponder;
-(void)setStringValue:(id)value;
-(void)appendString:(id)string;
-(void)deleteLastCharacter;
-(void)setPINPolicyString:(id)string visible:(BOOL)visible;
-(BOOL)textFieldShouldReturn:(id)textField;
@end

