/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSSetupController.h"


@interface DevicePINSetupController : PSSetupController {
	BOOL _success;
}
-(id)init;
-(BOOL)success;
-(BOOL)usePopupStyle;
-(BOOL)popupStyleIsModal;
@end

