/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSDetailController.h"

@class NSString;

@interface DevicePINController : PSDetailController {
	int _mode;
	int _substate;
	NSString* _lastEntry;
	BOOL _success;
	int _pinEntryMode;
	BOOL _pinEntryModeLoaded;
	NSString* _error1;
	NSString* _error2;
}
+(BOOL)settingEnabled;
-(void)willUnlock;
-(id)init;
-(CGSize)contentSizeForViewInPopover;
-(void)_dismiss;
-(id)stringsTable;
-(void)dealloc;
-(void)setLastEntry:(id)entry;
-(BOOL)pinIsAcceptable:(id)acceptable outError:(id*)error;
-(void)setPIN:(id)pin;
-(BOOL)validatePIN:(id)pin;
-(BOOL)useProgressiveDelays;
-(int)pinLength;
-(CFStringRef)defaultsID;
-(CFStringRef)failedAttemptsKey;
-(CFStringRef)blockTimeIntervalKey;
-(CFStringRef)blockedStateKey;
-(void)_loadPinEntryMode;
-(BOOL)requiresKeyboard;
-(BOOL)simplePIN;
-(BOOL)switchFromKeypadToKeyboard;
-(int)_numberOfFailedAttempts;
-(void)_setNumberOfFailedAttempts:(int)failedAttempts;
-(void)_clearBlockedState;
-(double)_unblockTime;
-(BOOL)_isBlocked;
-(void)_setUnblockTime:(double)time;
-(BOOL)_attemptValidationWithPIN:(id)pin;
-(void)performActionAfterPINEntry;
-(void)performActionAfterPINSetOrRemove;
-(void)performActionAfterPINSet;
-(void)performActionAfterPINRemove;
-(void)suspend;
-(void)_showFailedAttempts;
-(void)_updateErrorTextAndFailureCount:(BOOL)count;
-(void)_updateUI;
-(void)_showUnacceptablePINError:(id)error password:(id)password;
-(void)_showPINConfirmationError;
-(void)_updatePINButtons;
-(void)pinEntered:(id)entered;
-(void)cancelButtonTapped;
-(id)pinInstructionsPrompt;
-(id)pinInstructionsPromptFont;
-(void)viewDidAppear:(BOOL)view;
-(CGRect)paneFrame;
-(void)setPane:(id)pane;
-(BOOL)_success;
@end

