/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSEditingPane.h"
#import "UIKeyInput.h"

@class UITransitionView, UIResponder, UIKeyboard;
@protocol PINEntryView;

@interface DevicePINPane : PSEditingPane <UIKeyInput> {
	UITransitionView* _transitionView;
	UIView<PINEntryView>* _pinView;
	UIKeyboard* _keypad;
	UIResponder<UIKeyInput>* _savedKeyboardDelegate;
	BOOL _playSound;
	BOOL _transitioning;
	BOOL _isBlocked;
	CGRect _pinViewFrame;
	CGRect _keypadFrame;
	BOOL _simplePIN;
	int _autocapitalizationType;
	int _autocorrectionType;
	int _keyboardType;
	int _keyboardAppearance;
}
@property(assign, nonatomic) int autocapitalizationType;
@property(assign, nonatomic) int autocorrectionType;
@property(assign, nonatomic) int keyboardType;
@property(assign, nonatomic) int keyboardAppearance;
@property(assign, nonatomic) int returnKeyType;
@property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;
@property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
-(id)specifierLabel;
-(id)initWithFrame:(CGRect)frame;
-(void)_addKeypadView;
-(void)showFailedAttempts:(int)attempts;
-(void)hideFailedAttempts;
-(void)setSimplePIN:(BOOL)pin requiresKeyboard:(BOOL)keyboard;
-(BOOL)simplePIN;
-(BOOL)requiresKeyboard;
-(void)_setKeypadVisible:(BOOL)visible animated:(BOOL)animated;
-(void)dismissKeypad;
-(void)_switchToAlphanumericKeyboard:(BOOL)alphanumericKeyboard;
-(BOOL)becomeFirstResponder;
-(void)showError:(id)error error:(id)error2 isBlocked:(BOOL)blocked animate:(BOOL)animate;
-(void)setPINPolicyString:(id)string visible:(BOOL)visible;
-(void)okButtonPressed;
-(void)hideError;
-(void)setTitle:(id)title;
-(void)slidePasscodeField:(BOOL)field;
-(void)transitionViewDidComplete:(id)transitionView;
-(id)password;
-(void)clearPassword;
-(id)text;
-(void)setText:(id)text;
-(BOOL)hasText;
-(void)insertText:(id)text;
-(void)deleteBackward;
-(void)pinView:(id)view pinEntered:(id)entered;
@end

