/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import <UIKit/UIImageView.h>

@class UILabel;

@interface FailureBarView : UIImageView {
	UILabel* _titleLabel;
}
-(id)initWithFrame:(CGRect)frame;
-(void)setFailureCount:(int)count;
@end

