/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PINView.h"

@class UIPasscodeField;

@interface NumericPINView : PINView {
	UIPasscodeField* _passcodeField;
}
-(id)initWithFrame:(CGRect)frame;
-(void)hidePasscodeField:(BOOL)field;
-(id)stringValue;
-(void)setStringValue:(id)value;
-(void)deleteLastCharacter;
-(void)appendString:(id)string;
-(void)setPINPolicyString:(id)string visible:(BOOL)visible;
-(void)showFailedAttempts:(int)attempts;
@end

