/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */


@protocol PSController <NSObject>
-(void)setParentController:(id)controller;
-(id)parentController;
-(void)setRootController:(id)controller;
-(id)rootController;
-(void)setSpecifier:(id)specifier;
-(id)specifier;
-(void)suspend;
-(void)didLock;
-(void)willUnlock;
-(void)didUnlock;
-(void)didWake;
-(void)pushController:(id)controller;
-(void)handleURL:(id)url;
-(void)setPreferenceValue:(id)value specifier:(id)specifier;
-(id)readPreferenceValue:(id)value;
@end

