/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSTableCell.h"

@class UIControl, UIActivityIndicatorView, UIView, NSArray, NSDictionary;

@interface PSControlTableCell : PSTableCell {
	UIControl* _control;
	UIActivityIndicatorView* _activityIndicator;
	NSArray* _values;
	NSDictionary* _titleDict;
	UIView* _disabledView;
}
-(void)setCellEnabled:(BOOL)enabled;
-(void)setValues:(id)values titleDictionary:(id)dictionary;
-(void)setBackgroundView:(id)view;
-(id)titleLabel;
-(id)valueLabel;
-(void)dealloc;
-(id)control;
-(BOOL)loading;
-(void)setLoading:(BOOL)loading;
-(void)setControl:(id)control;
-(void)controlChanged:(id)changed;
-(void)setValue:(id)value;
-(void)layoutSubviews;
@end

