/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSListController.h"


@interface PSEditableListController : PSListController {
	BOOL _editable;
}
-(id)init;
-(void)_updateNavigationBar;
-(void)viewWillAppear:(BOOL)view;
-(void)pushController:(id)controller;
-(void)editDoneTapped;
-(BOOL)editable;
-(void)setEditable:(BOOL)editable;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(BOOL)performDeletionActionForSpecifier:(id)specifier;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
@end

