/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PreferencesTextTableCell.h"

@class PSSpecifier;

@interface PSEditableTableCell : PreferencesTextTableCell {
	PSSpecifier* _userInfo;
	SEL _targetSetter;
	id _realTarget;
	int _type;
	BOOL _valueChanged;
}
@property(assign, nonatomic) int type;
-(void)controlChanged:(id)changed;
-(void)_setValueChanged;
-(void)_saveForExit;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldDidEndEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)setValueChangedTarget:(id)target action:(SEL)action userInfo:(id)info;
-(void)dealloc;
@end

