/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSController.h"
#import <UIKit/UINavigationController.h>

@class PSSpecifier, NSMutableSet, NSString;

@interface PSRootController : UINavigationController <PSController> {
	NSString* _idStr;
	PSSpecifier* _specifier;
	NSMutableSet* _tasks;
	BOOL _deallocating;
	unsigned char _hasTelephony;
}
+(void)writePreference:(id)preference;
+(void)setPreferenceValue:(id)value specifier:(id)specifier;
+(id)readPreferenceValue:(id)value;
-(void)setPreferenceValue:(id)value specifier:(id)specifier;
-(id)readPreferenceValue:(id)value;
-(id)initWithTitle:(id)title identifier:(id)identifier;
-(BOOL)taskIsRunning:(id)running;
-(void)addTask:(id)task;
-(void)taskFinished:(id)finished;
-(BOOL)busy;
-(id)contentViewForTopController;
-(id)specifiers;
-(void)setParentController:(id)controller;
-(void)setSpecifier:(id)specifier;
-(id)specifier;
-(void)pushController:(id)controller;
-(void)handleURL:(id)url;
-(void)showLeftButton:(id)button withStyle:(int)style rightButton:(id)button3 withStyle:(int)style4;
-(void)suspend;
-(void)didLock;
-(void)willUnlock;
-(void)didUnlock;
-(void)didWake;
-(BOOL)deallocating;
-(BOOL)hasTelephony;
-(void)dealloc;
-(id)parentController;
-(void)lazyLoadBundle:(id)bundle;
-(void)setRootController:(id)controller;
-(id)rootController;
-(void)willDismissPopupView;
-(void)didDismissPopupView;
-(void)willDismissFormSheetView;
-(void)didDismissFormSheetView;
@end

