/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSRootController.h"

@class UIViewController, NSDictionary;

@interface PSSetupController : PSRootController {
	NSDictionary* _rootInfo;
	UIViewController<PSController>* _parentController;
	PSRootController* _parentRootController;
}
-(id)init;
-(void)dealloc;
-(id)parentController;
-(void)setupController;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)pushController:(id)controller;
-(void)setParentController:(id)controller;
-(id)controller;
-(void)dismiss;
-(void)pushControllerOnParentWithSpecifier:(id)specifier;
-(void)popControllerOnParent;
-(id)methodSignatureForSelector:(SEL)selector;
-(void)forwardInvocation:(id)invocation;
-(BOOL)usePopupStyle;
-(BOOL)popupStyleIsModal;
@end

