/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSArray, NSString, NSDictionary;

@interface PSSpecifier : NSObject {
	id target;
	SEL getter;
	SEL setter;
	SEL action;
	Class detailControllerClass;
	int cellType;
	Class editPaneClass;
	int keyboardType;
	int autoCapsType;
	int autoCorrectionType;
	int textFieldType;
	NSString* _name;
	NSArray* _values;
	NSDictionary* _titleDict;
	NSDictionary* _shortTitleDict;
	id _userInfo;
	NSMutableDictionary* _properties;
}
+(id)preferenceSpecifierNamed:(id)named target:(id)target set:(SEL)set get:(SEL)get detail:(Class)detail cell:(int)cell edit:(Class)edit;
+(id)groupSpecifierWithName:(id)name;
+(id)emptyGroupSpecifier;
+(int)autoCapsTypeForString:(id)string;
+(int)keyboardTypeForString:(id)string;
-(id)init;
-(id)propertyForKey:(id)key;
-(void)setProperty:(id)property forKey:(id)key;
-(void)removePropertyForKey:(id)key;
-(void)setProperties:(id)properties;
-(id)properties;
-(void)loadValuesAndTitlesFromDataSource;
-(void)setValues:(id)values titles:(id)titles;
-(void)setValues:(id)values titles:(id)titles shortTitles:(id)titles3;
-(void)setupIconImageWithPath:(id)path;
-(void)dealloc;
-(id)description;
-(id)name;
-(id)userInfo;
-(id)titleDictionary;
-(id)shortTitleDictionary;
-(id)identifier;
-(id)values;
-(void)setName:(id)name;
-(void)setUserInfo:(id)info;
-(void)setTitleDictionary:(id)dictionary;
-(void)setShortTitleDictionary:(id)dictionary;
-(void)setValues:(id)values;
-(void)setTarget:(id)target;
-(void)setKeyboardType:(int)type autoCaps:(int)caps autoCorrection:(int)correction;
-(int)titleCompare:(id)compare;
@end

