/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSTableCell.h"
#import "PreferencesTableCell.h"

@class UIView, PSSpecifier;

@interface PSTableCell : PreferencesTableCell {
	PSSpecifier* _userInfo;
	int _type;
	UIView* _topEtchLine;
	UIView* _bottomEtchLine;
	BOOL _etch;
}
@property(assign, nonatomic) int type;
+(int)cellTypeFromString:(id)string;
+(id)_cellForSpecifier:(id)specifier defaultClass:(Class)aClass type:(int)type;
+(id)switchCellWithSpecifier:(id)specifier;
+(id)segmentCellWithSpecifier:(id)specifier;
+(id)sliderCellWithSpecifier:(id)specifier;
+(id)textFieldCellWithSpecifier:(id)specifier;
+(id)textViewCellWithSpecifier:(id)specifier;
+(id)groupHeaderCellWithSpecifier:(id)specifier;
+(id)staticTextCellWithSpecifier:(id)specifier;
+(id)cellWithSpecifier:(id)specifier;
+(id)CreateTopEtchLineView;
+(id)CreateBottomEtchLineView;
-(void)layoutSubviews;
-(void)setUserInfo:(id)info;
-(id)userInfo;
-(void)setValueChangedTarget:(id)target action:(SEL)action userInfo:(id)info;
-(id)titleTextLabel;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier specifier:(id)specifier;
-(void)_updateEtchState:(BOOL)state;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setIcon:(id)icon;
-(void)dealloc;
-(void)willMoveToSuperview:(id)superview;
@end

@interface PSTableCell (SyntheticEvents)
-(id)_automationID;
-(id)scriptingInfoWithChildren;
@end

