/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSEditingPane.h"

@class UITextField;

@interface PSTextEditingPane : PSEditingPane {
	UITextField* _textField;
}
-(id)initWithFrame:(CGRect)frame;
-(BOOL)becomeFirstResponder;
-(void)setPreferenceValue:(id)value;
-(id)preferenceValue;
-(void)setPreferenceSpecifier:(id)specifier;
@end

