/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "UITextViewDelegate.h"
#import "PSTableCell.h"

@class PSTextView;

@interface PSTextViewTableCell : PSTableCell <UITextViewDelegate> {
	PSTextView* _textView;
}
-(void)setValue:(id)value;
-(void)textViewDidEndEditing:(id)textView;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(BOOL)resignFirstResponder;
-(id)textView;
-(void)setTextView:(id)view;
-(void)drawTitleInRect:(CGRect)rect selected:(BOOL)selected;
@end

