/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSController.h"
#import <UIKit/UIViewController.h>

@class PSSpecifier, PSRootController;

@interface PSViewController : UIViewController <PSController> {
	UIViewController<PSController>* _parentController;
	PSRootController* _rootController;
	PSSpecifier* _specifier;
}
-(id)init;
-(void)setParentController:(id)controller;
-(id)parentController;
-(void)setRootController:(id)controller;
-(id)rootController;
-(void)dealloc;
-(void)setSpecifier:(id)specifier;
-(id)specifier;
-(void)setPreferenceValue:(id)value specifier:(id)specifier;
-(id)readPreferenceValue:(id)value;
-(void)suspend;
-(void)didLock;
-(void)willUnlock;
-(void)didUnlock;
-(void)didWake;
-(void)pushController:(id)controller;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)handleURL:(id)url;
-(id)methodSignatureForSelector:(SEL)selector;
-(void)forwardInvocation:(id)invocation;
-(void)popupViewWillDisappear;
-(void)popupViewDidDisappear;
-(void)formSheetViewWillDisappear;
-(void)formSheetViewDidDisappear;
@end

