/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import <UIKit/UIView.h>

@class CALayer;

@interface SnapshotView : UIView {
	CALayer* _layerToSnapshot;
}
-(id)init;
-(void)drawRect:(CGRect)rect;
-(void)becomeSnapshotOfView:(id)view;
-(BOOL)becomeSnapshotOfTable:(id)table destinationFrame:(CGRect)frame;
@end

